export const videoChannel = [
    {
        "id":204951759,
        "title":"Every NYT front page since 1852",
        "description":"The news is breaking.",
        "url":"https:\/\/vimeo.com\/204951759",
        "upload_date":"2017-02-20 16:35:41",
        "thumbnail_small":"https:\/\/i.vimeocdn.com\/video\/619588786_100x75.webp",
        "thumbnail_medium":"https:\/\/i.vimeocdn.com\/video\/619588786_200x150.webp",
        "thumbnail_large":"https:\/\/i.vimeocdn.com\/video\/619588786_640.webp",
        "user_id":8747603,
        "user_name":"Josh Begley",
        "user_url":"https:\/\/vimeo.com\/joshbegley",
        "user_portrait_small":"https:\/\/i.vimeocdn.com\/portrait\/5642883_30x30.webp",
        "user_portrait_medium":"https:\/\/i.vimeocdn.com\/portrait\/5642883_75x75.webp",
        "user_portrait_large":"https:\/\/i.vimeocdn.com\/portrait\/5642883_100x100.webp",
        "user_portrait_huge":"https:\/\/i.vimeocdn.com\/portrait\/5642883_300x300.webp",
        "stats_number_of_likes":345,
        "stats_number_of_plays":0,
        "stats_number_of_comments":18,
        "duration":55,
        "width":2160,
        "height":2194,
        "tags":"",
        "embed_privacy":"anywhere"
    },
    {
        "id":204611433,
        "title":"GoPro Cause: Forever Securing World Food Supply with Crop Trust",
        "description":"Follow world-renowned scientist Cary Fowler into the heart of the arctic, where the Svalbard Global Seed Vault lies nestled in the frozen Norwegian landscape. Among the most important buildings in the world, the Seed Vault holds the key to human survival: more than 880,000 seed samples, the largest collection in the world. These seeds are critical because, unless safeguarded, agriculture biodiversity is at risk of decline in the face of changing environmental and population pressures. <br \/>\r\n<br \/>\r\nDonate today to join GoPro in supporting Crop Trust\u2019s Seed Vault to safeguard crop diversity, forever:<br \/>\r\nhttps:\/\/gopro.com\/goproforacause\/croptrust<br \/>\r\n<br \/>\r\nShot on the HERO4\u00ae camera from \u202ahttp:\/\/GoPro.com.<br \/>\r\n<br \/>\r\nAnimation and graphics by Uncle Ginger.<br \/>\r\nhttp:\/\/www.uncleginger.com\/<br \/>\r\n<br \/>\r\nTED Talks clips courtesy of TED conferences, LLC.<br \/>\r\n<br \/>\r\nAdditional footage provided by Getty Images and PBS Newshour.<br \/>\r\n<br \/>\r\nSpecial Thanks to: Cary Fowler, Martin Fowler, Sarah Arno, Amy Goldman, The Crop Trust, Brian Lainoff, Mark Lainoff, & the Svalbard community.<br \/>\r\n<br \/>\r\nTo license clips from this video go to https:\/\/licensing.gopro.com <br \/>\r\n<br \/>\r\nMusic<br \/>\r\n<br \/>\r\nWestern Skies Motel<br \/>\r\n\"3rd b #9\"<br \/>\r\n\"3rd b #5\"<br \/>\r\n<br \/>\r\nAdditional Music Courtesy of Score Revolution<br \/>\r\nhttp:\/\/scorerevolution.com\/<br \/>\r\n<br \/>\r\nAdditional Music Courtesy of ExtremeMusic<br \/>\r\nhttps:\/\/www.extrememusic.com\/<br \/>\r\n<br \/>\r\n<br \/>\r\nFor more from GoPro, follow us:<br \/>\r\nFacebook: https:\/\/www.facebook.com\/gopro<br \/>\r\nTwitter: https:\/\/twitter.com\/gopro<br \/>\r\nInstagram: https:\/\/instagram.com\/gopro<br \/>\r\nTumblr: http:\/\/gopro.tumblr.com\/<br \/>\r\nPinterest: http:\/\/www.pinterest.com\/gopro   <br \/>\r\nInside Line: https:\/\/gopro.com\/news",
        "url":"https:\/\/vimeo.com\/204611433",
        "upload_date":"2017-02-17 17:24:19",
        "thumbnail_small":"https:\/\/i.vimeocdn.com\/video\/619613547_100x75.webp",
        "thumbnail_medium":"https:\/\/i.vimeocdn.com\/video\/619613547_200x150.webp",
        "thumbnail_large":"https:\/\/i.vimeocdn.com\/video\/619613547_640.webp",
        "user_id":619797,
        "user_name":"GoPro",
        "user_url":"https:\/\/vimeo.com\/gopro",
        "user_portrait_small":"https:\/\/i.vimeocdn.com\/portrait\/6423906_30x30.webp",
        "user_portrait_medium":"https:\/\/i.vimeocdn.com\/portrait\/6423906_75x75.webp",
        "user_portrait_large":"https:\/\/i.vimeocdn.com\/portrait\/6423906_100x100.webp",
        "user_portrait_huge":"https:\/\/i.vimeocdn.com\/portrait\/6423906_300x300.webp",
        "stats_number_of_likes":202,
        "stats_number_of_plays":0,
        "stats_number_of_comments":7,
        "duration":976,
        "width":2560,
        "height":1080,
        "tags":"",
        "embed_privacy":"anywhere"
    },
    {
        "id":182931935,
        "title":"KHRUANGBIN: Two Fish and an Elephant",
        "description":"The story of a final goodbye and one last dance, based on the Khruangbin song, 'Two Fish and an Elephant'.<br \/>\r\n<br \/>\r\nMusic video for 'Two Fish And An Elephant' by Khruangbin<br \/>\r\nWriter and Director: Scott Dungate<br \/>\r\nTwo Fish: Chihiro Kawasaki<br \/>\r\nThe Elephant: Hugo Luck<br \/>\r\nExecutive Producer: Paul Glancy<br \/>\r\n<br \/>\r\nSomesuch Production Company<br \/>\r\nExecutive Producers: Tim Nash and Sally Campbell<br \/>\r\nHead of Music Videos: Hannah Turnbull-Walter<br \/>\r\nHead of Content: Sarah Pearson<br \/>\r\nProducer: Tom Gardner<br \/>\r\nDirector of Photography: Jackson Hunt<br \/>\r\nProduction Designer: Sam Tidman<br \/>\r\nChoreographer: Alexandra Green<br \/>\r\nCostume Designer: Gleb Ignatov<br \/>\r\nCasting Director: Leanne Flinn<br \/>\r\nProduction Manager: Elly Camisa<br \/>\r\nGaffer: Phil Penfold<br \/>\r\nHair and Make Up Artist: Gaby Winwood<br \/>\r\nLocation Manager: Thomas Gale<br \/>\r\n<br \/>\r\nWieden + Kennedy<br \/>\r\nExecutive Producer: Danielle Stewart<br \/>\r\nArt Direction and Titles: Cal Al-Jorani<br \/>\r\nMotion Graphics: Jon Harris<br \/>\r\nBTS and Stills Photographer: Ben Hutton<br \/>\r\nPR: Madoka Shimotsunuki<br \/>\r\n<br \/>\r\nKickstarter Campaign Team<br \/>\r\nSocial Strategist: Rob Meldrum<br \/>\r\nKick Starter Video and Stills: Dan Smith<br \/>\r\nStory Board Illustrator: Hiro Enoki<br \/>\r\nPR: Heidi Atwal, Lucy Murray Wills<br \/>\r\n<br \/>\r\nTRIM Edit House<br \/>\r\nEditor: Paul Hardcastle<br \/>\r\nEditor\u2019s Assistant: Ed Hanbury<br \/>\r\n<br \/>\r\nTHE MILL Post Production Company<br \/>\r\nShoot Supervisor: Gareth Brannan, Liz Mitchell, Sal Wilson <br \/>\r\n2D Lead Artist: Gareth Brannan, Sal Wilson, Warren Gebhardt <br \/>\r\n2D Artists: Jeanette Eiternes<br \/>\r\n3D Artists: Philip Maddock, Nico Domerego, Vicky McIntyre, Pavel Mamichev <br \/>\r\nMatte Painting: Aurelien Ronceray <br \/>\r\nColourist: James Bamford <br \/>\r\nProducer: George Reid <br \/>\r\n<br \/>\r\nFACTORY Sound design and Mix<br \/>\r\nSupervising Sound Editor: Anthony Moore<br \/>\r\nSound Designer: Jon Clarke<br \/>\r\nRe-recording Mixers: Jon Clarke and Anthony Moore<br \/>\r\nProducer: Lou Allen",
        "url":"https:\/\/vimeo.com\/182931935",
        "upload_date":"2016-09-15 19:16:30",
        "thumbnail_small":"https:\/\/i.vimeocdn.com\/video\/595036537_100x75.webp",
        "thumbnail_medium":"https:\/\/i.vimeocdn.com\/video\/595036537_200x150.webp",
        "thumbnail_large":"https:\/\/i.vimeocdn.com\/video\/595036537_640.webp",
        "user_id":1491784,
        "user_name":"scotty_fingers",
        "user_url":"https:\/\/vimeo.com\/scottdungate",
        "user_portrait_small":"https:\/\/i.vimeocdn.com\/portrait\/1852754_30x30.webp",
        "user_portrait_medium":"https:\/\/i.vimeocdn.com\/portrait\/1852754_75x75.webp",
        "user_portrait_large":"https:\/\/i.vimeocdn.com\/portrait\/1852754_100x100.webp",
        "user_portrait_huge":"https:\/\/i.vimeocdn.com\/portrait\/1852754_300x300.webp",
        "duration":444,
        "width":1280,
        "height":720,
        "tags":"Musicvideo, MV, Khruangbin, Director",
        "embed_privacy":"anywhere"
    },
    {
        "id":188075559,
        "title":"Black Holes",
        "description":"Black Holes is a 3D animated short film selected at Sundance 2017 that we\u2019re developing into an adult animated sitcom. We just launched a Kickstarter campaign to fund Season 1: www.bit.do\/blackholeskick<br \/>\r\n<br \/>\r\nAvailable w\/ French, Spanish subtitles.<br \/>\r\n<br \/>\r\nThis first season chronicles the journey of Dave The Astronaut and his partner, an intelligent melon, as they embark on the first ever human mission to Mars.",
        "url":"https:\/\/vimeo.com\/188075559",
        "upload_date":"2016-10-19 21:01:30",
        "thumbnail_small":"https:\/\/i.vimeocdn.com\/video\/619722398_100x75.webp",
        "thumbnail_medium":"https:\/\/i.vimeocdn.com\/video\/619722398_200x150.webp",
        "thumbnail_large":"https:\/\/i.vimeocdn.com\/video\/619722398_640.webp",
        "user_id":35858813,
        "user_name":"NOODLES",
        "user_url":"https:\/\/vimeo.com\/user35858813",
        "user_portrait_small":"https:\/\/i.vimeocdn.com\/portrait\/8927943_30x30.webp",
        "user_portrait_medium":"https:\/\/i.vimeocdn.com\/portrait\/8927943_75x75.webp",
        "user_portrait_large":"https:\/\/i.vimeocdn.com\/portrait\/8927943_100x100.webp",
        "user_portrait_huge":"https:\/\/i.vimeocdn.com\/portrait\/8927943_300x300.webp",
        "stats_number_of_likes":376,
        "stats_number_of_plays":730,
        "stats_number_of_comments":21,
        "duration":734,
        "width":1888,
        "height":1062,
        "tags":"animation, short film, sundance, kickstarter",
        "embed_privacy":"anywhere"
    }
]
